### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by tecmry** [chaoyuaw/pytorch-coviar#30]
which version of Pytorch is used in this project?

**Comment by chaoyuaw** [comment]
I used PyTorch 0.3.0.post4

**Comment by TyroneLi** [comment]
> I used PyTorch 0.3.0.post4
@chaoyuaw Hi~Do you know how to train using pytorch1.1. I tried training using pytorch-1.1,but I got such error:
`Augmentation scales: [1, 0.875, 0.75, 0.66]
3570 videos loaded.
1530 videos loaded.
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
Traceback (most recent call last):
  File "train.py", line 271, in <module>
    main()
  File "train.py", line 102, in main
    train(train_loader, model, criterion, optimizer, epoch, cur_lr)
  File "train.py", line 138, in train
    output = model(input_var)
  File "/home/lijinlong/anaconda3/envs/pytorch_seg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lijinlong/anaconda3/envs/pytorch_seg/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/lijinlong/anaconda3/envs/pytorch_seg/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/lijinlong/anaconda3/envs/pytorch_seg/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/lijinlong/anaconda3/envs/pytorch_seg/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/lijinlong/anaconda3/envs/pytorch_seg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lijinlong/codebase/projects/pytorch-coviar/model.py", line 64, in forward
    base_out = self.base_model(input)
  File "/home/lijinlong/anaconda3/envs/pytorch_seg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lijinlong/anaconda3/envs/pytorch_seg/lib/python3.6/site-packages/torchvision/models/resnet.py", line 192, in forward
    x = self.conv1(x)
  File "/home/lijinlong/anaconda3/envs/pytorch_seg/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lijinlong/anaconda3/envs/pytorch_seg/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383`
Do you know how to fix this?Or is this a bug or just because of the version of pytorch?
if possible, how could I migrate your project into pytorch-1.1?
Hope for your reply
