### ISSUE TITLE
To combine the results and calculate the final accuracy.

### ISSUE THREAD

**Issue by kanzaali** [chaoyuaw/pytorch-coviar#57]
When I run combine.py, I am facing following error: 

Traceback (most recent call last):
  File "combine.py", line 48, in <module>
    main()
  File "combine.py", line 24, in main
    with np.load(args.iframe) as iframe:
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/npyio.py", line 384, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '.npz'

**Comment by chaoyuaw** [comment]
Hi, thanks for your question!

Please replace the ${iframe_score_file}, ${mv_score_file}, and ${residual_score_file} in 

"""
python combine.py --iframe ${iframe_score_file} \
	--mv ${mv_score_file} \
	--res ${residual_score_file}
"""

to be the actual score file names. Please let me know if that solves the issue.

**Comment by kanzaali** [comment]
Hi, Thanks for your reply. 

I replaced with actual file name already. I have run the combined file before too but dont know, now it says that there is no .npz file. though they are in the folder.

**Comment by kanzaali** [comment]
BTW I want to accumulate results for I and MV frames only.
